DROP TABLE IF EXISTS subcomments CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS image CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS password CASCADE;
DROP TABLE IF EXISTS follows CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS fbuser CASCADE;
DROP DOMAIN IF EXISTS GENDER CASCADE;

DROP SEQUENCE IF EXISTS uid CASCADE;
DROP SEQUENCE IF EXISTS postid CASCADE;
DROP SEQUENCE IF EXISTS imageid CASCADE;
DROP SEQUENCE IF EXISTS commentid CASCADE;
